minimumReleaseAgeExclude:
  - bullmq@5.81.2
allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: false
  postgres-memory-server: true
  prisma: set this to true or false
  redis-memory-server: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
