minimumReleaseAgeExclude:
  - bullmq@5.81.2
allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: false
  postgres-memory-server: true
  prisma: true
  redis-memory-server: true
  sharp: true
  unrs-resolver: true
